"""
Elezzjoni.mt — Candidate Enrichment Pipeline
=============================================

Reads candidates from Supabase and runs each through four stages:

  1. DISCOVER  — finds Facebook page + website via manual overrides → Wikidata
  2. SCRAPE    — pulls content in priority order:
                   a) Facebook (Playwright, optionally authenticated via state.json)
                   b) Personal website (trafilatura — strips navs/footers automatically)
                   c) Local news search (DuckDuckGo → trafilatura on first result)
  3. ENRICH    — llama3.1:8b running locally via Ollama scores the candidate's
                 independence from their party brand and extracts stances + quotes
  4. SAVE      — upserts the following columns back to Supabase:
                   party_reliance_score  INTEGER  (0 = fully independent, 100 = party mouthpiece)
                   score_justification   TEXT
                   personal_stances      TEXT[]   (up to 4 policy stances)
                   key_quotes            TEXT[]   (up to 3 direct quotes)
                   photo_url             TEXT

Run:
  cd pipeline
  cp ../.env.local .env
  pip install -r requirements.txt
  playwright install chromium
  python scraper.py

Facebook auth (optional — gets past login walls):
  playwright codegen --save-storage=state.json https://www.facebook.com
  Log in manually, then Ctrl+C. Re-run scraper.py — it will pick up state.json.

Env overrides:
  ENRICH_ALL_OVERRIDE=true   re-process candidates that already have scores
  DRY_RUN_OVERRIDE=true      print what would be written; don't touch Supabase
  SKIP_DISCOVERY=true        skip link discovery (use social_links already in DB)
"""

import asyncio
import json
import os
import re
import subprocess
from datetime import datetime, timezone

import httpx
import trafilatura
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from playwright.async_api import async_playwright, Browser
from supabase import create_client, Client

load_dotenv(dotenv_path=".env")

# ── Config ────────────────────────────────────────────────────────────────────

SUPABASE_URL              = os.environ.get("SUPABASE_URL") or os.environ["NEXT_PUBLIC_SUPABASE_URL"]
SUPABASE_SERVICE_ROLE_KEY = os.environ["SUPABASE_SERVICE_ROLE_KEY"]

OLLAMA_URL   = "http://localhost:11434"
OLLAMA_MODEL = "llama3.1:8b"
WIKIPEDIA_API  = "https://en.wikipedia.org/w/api.php"
DDG_SEARCH_URL = "https://html.duckduckgo.com/html/"

# Minimum words from any single source before we consider it usable
MIN_WORDS = 100

# Maltese news sites targeted in the news search Google dork
MALTESE_NEWS_SITES = [
    "timesofmalta.com",
    "maltatoday.com.mt",
    "independent.com.mt",
    "newsbook.com.mt",
]

SKIP_DISCOVERY = os.environ.get("SKIP_DISCOVERY",       "").lower() == "true"
ENRICH_ALL     = os.environ.get("ENRICH_ALL_OVERRIDE",  "").lower() == "true"
DRY_RUN        = os.environ.get("DRY_RUN_OVERRIDE",     "").lower() == "true"

# Path to Playwright auth state — generated by: playwright codegen --save-storage=state.json
STATE_JSON = os.path.join(os.path.dirname(__file__), "state.json")

UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/124.0.0.0 Safari/537.36"
)

# ── Text validation ───────────────────────────────────────────────────────────

# Phrases that indicate a login wall or generic boilerplate rather than real content
_BOILERPLATE_SIGNALS = [
    "log in to facebook", "log into facebook", "create new account",
    "forgotten password", "forgot password", "sign up for facebook",
    "facebook login", "you must log in", "allow all cookies",
    "see more on facebook", "connect with friends", "see photos and videos",
    "to see more from", "sign in to continue", "join facebook",
    "cookie policy", "privacy policy", "terms of service",
]


def is_valid_political_text(text: str) -> bool:
    """
    Returns False if the text is dominated by login-wall / cookie-banner
    boilerplate rather than real candidate content.
    Checks both hard phrase matches and a boilerplate-density heuristic.
    """
    if not text or len(text.split()) < 30:
        return False

    lower = text.lower()

    # Hard reject: any login-wall phrase present
    if any(sig in lower for sig in _BOILERPLATE_SIGNALS):
        return False

    return True


SYSTEM_PROMPT = (
    "You are analyzing text about a Maltese local council candidate. "
    "The text may be a first-person social media post OR a third-person news article. "
    "Extract their policy stances and quotes. "
    "Calculate an 'Independence Score' (party_reliance_score) from 0-100 where 100 means "
    "they heavily promote their political party, and 0 means they promote their own "
    "independent personal brand and local vision. "
    "Look for pronouns ('I' vs 'We'), references to the party leader, and mentions of "
    "party manifestos to inform the score. "
    "If the text is purely biographical or academic with absolutely no political or policy "
    "content, output a score of -1. "
    "Return ONLY a valid JSON object with exactly these keys: "
    "party_reliance_score (integer 0-100, or -1 if no political content), "
    "score_justification (string, 1-2 sentences), "
    "personal_stances (array of up to 4 strings, third person, max 25 words each), "
    "key_quotes (array of up to 3 direct quote strings). No markdown, no extra text."
)


# ── Ollama lifecycle ──────────────────────────────────────────────────────────

async def ensure_ollama_running() -> subprocess.Popen | None:
    """
    Checks if Ollama is already running. If not, starts it as a background
    subprocess and waits up to 20 seconds for it to be ready.
    Returns the Popen object if we started it (so main() can stop it later),
    or None if it was already running.
    """
    async with httpx.AsyncClient() as c:
        try:
            await c.get(f"{OLLAMA_URL}/api/tags", timeout=2)
            return None   # already running
        except Exception:
            pass

    print("  🦙 starting Ollama…")
    proc = subprocess.Popen(
        ["ollama", "serve"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Poll until the server is ready (up to 20s)
    for _ in range(40):
        await asyncio.sleep(0.5)
        try:
            async with httpx.AsyncClient() as c:
                await c.get(f"{OLLAMA_URL}/api/tags", timeout=2)
            print("  ✓  Ollama ready\n")
            return proc
        except Exception:
            continue

    proc.terminate()
    raise RuntimeError("Ollama failed to start within 20 seconds — is it installed? (brew install ollama)")

# ── Known name overrides ──────────────────────────────────────────────────────

# DB name → Wikipedia article title (only needed when they differ)
WIKIPEDIA_OVERRIDES: dict[str, str] = {
    "Ivan J Bartolo":             "Ivan J. Bartolo",
    "Jo Etienne Abela":           "Joe Abela (politician)",
    "Robert Abela":               "Robert Abela (politician)",
    "Joe Mizzi":                  "Joe Mizzi (politician)",
    "Marie Louise Coleiro Preca": "Marie Louise Coleiro Preca",
}

# Manually curated Facebook page URLs — used before Wikidata lookup
FACEBOOK_OVERRIDES: dict[str, str] = {
    "Robert Abela":              "https://www.facebook.com/robertabela.mt",
    "Bernard Grech":             "https://www.facebook.com/bernardgrechmt",
    "Chris Fearne":              "https://www.facebook.com/chrisfearne.mt",
    "Ian Borg":                  "https://www.facebook.com/IanBorgMalta",
    "Clyde Caruana":             "https://www.facebook.com/ClydeCaruanaOfficial",
    "Silvio Schembri":           "https://www.facebook.com/SilvioSchembri",
    "Owen Bonnici":              "https://www.facebook.com/owenbonnici",
    "Clayton Bartolo":           "https://www.facebook.com/claytonbartolomalta",
    "Julia Farrugia Portelli":   "https://www.facebook.com/JuliaFarrugiaPortelli",
    "Jo Etienne Abela":          "https://www.facebook.com/JoEtienneAbela",
    "Stefan Zrinzo Azzopardi":   "https://www.facebook.com/StefanZrinzoAzzopardi",
    "Clint Camilleri":           "https://www.facebook.com/ClintCamilleriMalta",
    "Miriam Dalli":              "https://www.facebook.com/miriamdalliofficial",
    "Edward Zammit Lewis":       "https://www.facebook.com/EdwardZammitLewis",
    "Rosianne Cutajar":          "https://www.facebook.com/RosianneOfficial",
    "Alex Muscat":               "https://www.facebook.com/alexmuscatmp",
    "Randolph De Battista":      "https://www.facebook.com/randolphdebattista",
    "Michael Farrugia":          "https://www.facebook.com/MichaelFarrugiaMP",
    "Anton Refalo":              "https://www.facebook.com/antonrefalo",
    "Roderick Galdes":           "https://www.facebook.com/roderickgaldes",
    "Clifton Grima":             "https://www.facebook.com/CliftonGrima",
    "Rebecca Buttigieg":         "https://www.facebook.com/RebeccaButtigiegMP",
    "Omar Farrugia":             "https://www.facebook.com/OmarFarrugiaMalta",
    "Malcolm Paul Agius Galea":  "https://www.facebook.com/malcolmpaulagiusgalea",
    "Romilda Baldacchino Zarb":  "https://www.facebook.com/romildabaldacchinozarb",
    "Michael Falzon":            "https://www.facebook.com/michaelfalzonmp",
    "Deo Debattista":            "https://www.facebook.com/deodebattista",
    "Toni Bezzina":              "https://www.facebook.com/tonibezzina.mp",
    "Ian Vassallo Hagi":         "https://www.facebook.com/IanVassalloHagi",
    "Naomi Cachia":              "https://www.facebook.com/naomicachiaPN",
    "Davina Sammut Hili":        "https://www.facebook.com/DavinaSammutHili",
    "Amanda Spiteri Grech":      "https://www.facebook.com/amandaspiteri.grech",
    "Abigail Camilleri":         "https://www.facebook.com/AbigailCamilleriMalta",
    "Cressida Galea":            "https://www.facebook.com/CressidaGalea",
    "Alicia Bugeja Said":        "https://www.facebook.com/AliciaBugejaSaid",
    "Clayton Camilleri":         "https://www.facebook.com/claytonpcamilleri",
    "Claudette Buttigieg":       "https://www.facebook.com/ClaudetteButtigieg",
    "David Casa":                "https://www.facebook.com/DavidCasaMEP",
    "Francis Zammit Dimech":     "https://www.facebook.com/FrancisZammitDimech",
    "Hermann Schiavone":         "https://www.facebook.com/HermannSchiavone",
    "Ivan Bartolo":              "https://www.facebook.com/IvanBartoloPn",
    "Joe Ellis":                 "https://www.facebook.com/JoeEllisMalta",
    "Karl Gouder":               "https://www.facebook.com/KarlGouderPN",
    "Mark Anthony Sammut":       "https://www.facebook.com/MarkAnthonySammut",
    "Peter Agius":               "https://www.facebook.com/PeterAgiusPN",
    "Ryan Callus":               "https://www.facebook.com/RyanCallusPN",
}

WIKIDATA_HEADERS = {"User-Agent": "ElezzjoniMT/1.0 (jacxuereb@gmail.com)", "Accept": "application/json"}


# ── Stage 1: Discover social links ───────────────────────────────────────────

async def wikidata_lookup(name: str, client: httpx.AsyncClient) -> tuple[str | None, str | None, str | None]:
    """
    Returns (facebook_url, website_url, photo_url) from Wikidata.
    Properties: P2013 (Facebook username), P856 (official website), P18 (image).
    """
    try:
        resp = await client.get(
            "https://www.wikidata.org/w/api.php",
            params={"action": "wbsearchentities", "search": name, "language": "en",
                    "format": "json", "limit": 3},
            headers=WIKIDATA_HEADERS, timeout=10,
        )
        results = resp.json().get("search", [])

        # Pick the first result that looks Maltese/political
        qid = None
        for r in results:
            desc = r.get("description", "").lower()
            if any(w in desc for w in ["malta", "maltese", "politician", "minister", "mep"]):
                qid = r["id"]
                break
        if not qid:
            return None, None, None

        resp2 = await client.get(
            "https://www.wikidata.org/w/api.php",
            params={"action": "wbgetentities", "ids": qid, "props": "claims", "format": "json"},
            headers=WIKIDATA_HEADERS, timeout=10,
        )
        claims = resp2.json()["entities"][qid].get("claims", {})

        fb_slug  = claims.get("P2013", [{}])[0].get("mainsnak", {}).get("datavalue", {}).get("value")
        fb_url   = f"https://www.facebook.com/{fb_slug}" if fb_slug else None
        web_url  = claims.get("P856", [{}])[0].get("mainsnak", {}).get("datavalue", {}).get("value")
        photo_fn = claims.get("P18",  [{}])[0].get("mainsnak", {}).get("datavalue", {}).get("value", {})

        photo_url = None
        if isinstance(photo_fn, str) and photo_fn:
            from urllib.parse import quote
            encoded   = quote(photo_fn.replace(" ", "_"), safe="")
            photo_url = f"https://commons.wikimedia.org/wiki/Special:FilePath/{encoded}?width=400"

        return fb_url, web_url, photo_url

    except Exception as e:
        print(f"    ⚠ Wikidata error for '{name}': {e}")
        return None, None, None


async def discover_links(name: str, client: httpx.AsyncClient) -> tuple[str | None, str | None]:
    """
    Returns (facebook_url, website_url).
    Priority: FACEBOOK_OVERRIDES → Wikidata.
    """
    fb_url  = FACEBOOK_OVERRIDES.get(name)
    web_url = None

    # Always check Wikidata for the website URL regardless of FB override
    wd_fb, wd_web, _ = await wikidata_lookup(name, client)
    if not fb_url:
        fb_url = wd_fb
    web_url = wd_web

    return fb_url, web_url


# ── Stage 2a: Scrape Facebook posts ──────────────────────────────────────────

async def scrape_facebook(url: str, browser: Browser) -> str:
    """
    Loads a public Facebook page and returns post text.
    Uses the mobile site which is easier to parse.

    If state.json exists it loads that auth session, bypassing the login wall.
    Falls back to anonymous scraping if the file is missing.
    """
    mobile_url = re.sub(r"https?://(www\.)?facebook\.com", "https://m.facebook.com", url)

    ctx_kwargs: dict = {
        "user_agent": UA,
        "locale":     "en-MT",
        "viewport":   {"width": 390, "height": 844},
    }

    # Load saved auth session if available
    if os.path.exists(STATE_JSON):
        ctx_kwargs["storage_state"] = STATE_JSON
        print(f"   🔑 using saved Facebook session")

    try:
        ctx  = await browser.new_context(**ctx_kwargs)
        page = await ctx.new_page()

        await page.goto(mobile_url, wait_until="domcontentloaded", timeout=20_000)
        await page.wait_for_timeout(3000)

        html = await page.content()
        await ctx.close()

        soup = BeautifulSoup(html, "html.parser")
        for tag in soup(["script", "style", "nav", "header", "footer"]):
            tag.decompose()

        texts: list[str] = []

        # Mobile FB wraps posts in <article> elements
        for article in soup.find_all("article"):
            t = article.get_text(" ", strip=True)
            if len(t) > 40:
                texts.append(t)

        # Fallback: grab any substantial paragraph/div text
        if not texts:
            for p in soup.find_all(["p", "div"]):
                t = p.get_text(" ", strip=True)
                if 80 < len(t) < 2000 and len(t.split()) > 12:
                    texts.append(t)

        combined = "\n\n".join(dict.fromkeys(texts))

        if not is_valid_political_text(combined):
            print(f"   ⚠ Facebook login wall / boilerplate — run: playwright codegen --save-storage=state.json https://www.facebook.com")
            return ""

        return combined[:8000]

    except Exception as e:
        print(f"    ⚠ Facebook scrape error ({url}): {e}")
        return ""


def _og_image(html: str) -> str | None:
    """Extracts og:image (or twitter:image) from an HTML page — reliable headshot source."""
    soup = BeautifulSoup(html, "html.parser")
    for attr in ("og:image", "twitter:image"):
        tag = soup.find("meta", property=attr) or soup.find("meta", attrs={"name": attr})
        if tag:
            content = tag.get("content", "").strip()
            if content.startswith("http"):
                return content
    return None


# ── Stage 2b: Scrape personal website ────────────────────────────────────────

async def scrape_website(url: str, client: httpx.AsyncClient) -> tuple[str, str | None]:
    """
    Fetches a personal/campaign website.
    Returns (body_text, og_image_url). Either can be empty/None on failure.
    trafilatura strips navs, footers, cookie banners automatically.
    """
    try:
        resp = await client.get(url, timeout=15, follow_redirects=True)
        text = await asyncio.to_thread(
            trafilatura.extract,
            resp.text,
            include_comments=False,
            include_tables=False,
            no_fallback=False,
        )
        photo = _og_image(resp.text)
        return (text[:6000] if text else ""), photo
    except Exception as e:
        print(f"    ⚠ Website scrape error ({url}): {e}")
    return "", None


# ── Stage 2c: Local news search fallback ─────────────────────────────────────

async def scrape_news(name: str, client: httpx.AsyncClient) -> tuple[str, str | None]:
    """
    Uses a Google dork targeting top Maltese journalism sites to find articles
    about the candidate, then extracts text + og:image via trafilatura.
    Returns (text, og_image_url).
    """
    site_filter = " OR ".join(f"site:{s}" for s in MALTESE_NEWS_SITES)
    query = f'"{name}" ({site_filter})'

    try:
        resp = await client.post(
            DDG_SEARCH_URL,
            data={"q": query, "b": "", "kl": ""},
            headers={"User-Agent": UA, "Content-Type": "application/x-www-form-urlencoded"},
            timeout=15,
            follow_redirects=True,
        )
        soup = BeautifulSoup(resp.text, "html.parser")

        # Collect URLs that belong to one of our target news sites
        result_urls: list[str] = []
        for a in soup.select("a.result__a"):
            href = a.get("href", "")
            if href.startswith("http") and any(site in href for site in MALTESE_NEWS_SITES):
                result_urls.append(href)
            if len(result_urls) >= 3:
                break

        for article_url in result_urls:
            try:
                article_resp = await client.get(article_url, timeout=12, follow_redirects=True)
                text = await asyncio.to_thread(
                    trafilatura.extract,
                    article_resp.text,
                    include_comments=False,
                    include_tables=False,
                    no_fallback=False,
                )
                if text and len(text.split()) >= MIN_WORDS:
                    print(f"   📰 {article_url}")
                    photo = _og_image(article_resp.text)
                    return text[:5000], photo
            except Exception:
                continue

    except Exception as e:
        print(f"    ⚠ News search error for '{name}': {e}")

    return "", None


# ── Stage 3: LLM enrichment via Ollama ───────────────────────────────────────

def build_prompt(name: str, source_label: str, text: str) -> str:
    return (
        f"The following text comes from {name}'s {source_label} — their own words "
        f"or news coverage about them.\n\n"
        f"Candidate name: {name}\n\n"
        f"Text:\n\"\"\"\n{text}\n\"\"\""
    )


async def enrich(name: str, text: str, source_label: str) -> dict:
    """
    Calls llama3.1:8b via Ollama to score party reliance and extract stances
    + quotes. The `format: "json"` option constrains the model to valid JSON.
    Returns a dict with all four fields, or empty dict on failure.
    """
    if not text or len(text.strip()) < 80:
        return {}

    prompt = build_prompt(name, source_label, text[:6000])

    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                f"{OLLAMA_URL}/api/chat",
                json={
                    "model":  OLLAMA_MODEL,
                    "format": "json",
                    "stream": False,
                    "options": {"temperature": 0.2},
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user",   "content": prompt},
                    ],
                },
                timeout=120,   # local inference on 8b can take ~30-60s cold
            )
        raw = resp.json()["message"]["content"].strip()
        # Strip any accidental markdown fences
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$",           "", raw)
        data = json.loads(raw)
        data["personal_stances"]     = data.get("personal_stances", [])[:4]
        data["key_quotes"]           = data.get("key_quotes",       [])[:3]
        score = int(data.get("party_reliance_score", 50))
        data["party_reliance_score"] = score
        # -1 means "no political content" — treat as no enrichment
        if score == -1:
            return {}
        return data

    except Exception as e:
        print(f"    ⚠ LLM error for '{name}': {e}")
        return {}


# ── Translation ───────────────────────────────────────────────────────────────

async def translate_to_maltese(texts: list[str]) -> list[str]:
    """
    Translates a list of English strings to Maltese using the MyMemory free
    REST API (no key needed, 1000 req/day free tier).
    Falls back to the original English string on any error.
    """
    results: list[str] = []
    async with httpx.AsyncClient() as client:
        for text in texts:
            if not text or not text.strip():
                results.append(text)
                continue
            try:
                resp = await client.get(
                    "https://api.mymemory.translated.net/get",
                    params={"q": text, "langpair": "en|mt"},
                    timeout=10,
                )
                data = resp.json()
                translated = data.get("responseData", {}).get("translatedText", "")
                # MyMemory returns the original text when it can't translate
                results.append(translated if translated else text)
            except Exception:
                results.append(text)   # fall back to English silently
    return results


# ── Photo: Facebook Graph API ─────────────────────────────────────────────────

async def fetch_facebook_photo(fb_url: str, client: httpx.AsyncClient) -> str | None:
    """
    Fetches the profile picture for a public Facebook page via the Graph API
    picture endpoint — no login, no Playwright needed.

    e.g. https://www.facebook.com/robertabela.mt
      →  GET graph.facebook.com/robertabela.mt/picture?type=large&redirect=false
    """
    m = re.search(r"facebook\.com/(?:pages/[^/]+/)?([^/?#]+)", fb_url)
    if not m:
        return None
    slug = m.group(1).rstrip("/")

    for size in ("large", "normal"):
        try:
            resp = await client.get(
                f"https://graph.facebook.com/{slug}/picture",
                params={"type": size, "redirect": "false"},
                timeout=10,
            )
            data = resp.json().get("data", {})
            if not data.get("is_silhouette", True):
                url = data.get("url")
                if url and url.startswith("http"):
                    return url
        except Exception:
            pass

    return None


# ── Photo: Wikipedia thumbnail fallback ──────────────────────────────────────

async def fetch_wikipedia_photo(name: str, client: httpx.AsyncClient) -> str | None:
    """Grabs a thumbnail from Wikipedia as a last resort for photos."""
    parts = name.split()
    candidates = [
        WIKIPEDIA_OVERRIDES.get(name, name),
        f"{parts[0]} {parts[-1]}" if len(parts) > 2 else name,
        f"{parts[0]} {parts[-1]} (politician)" if len(parts) >= 2 else name,
    ]
    seen: set[str] = set()
    for title in candidates:
        if title in seen:
            continue
        seen.add(title)
        try:
            resp = await client.get(
                WIKIPEDIA_API,
                params={"action": "query", "titles": title, "prop": "pageimages",
                        "pithumbsize": 400, "format": "json", "redirects": 1},
                timeout=10,
            )
            for page in resp.json().get("query", {}).get("pages", {}).values():
                if page.get("pageid", -1) != -1:
                    src = page.get("thumbnail", {}).get("source")
                    if src:
                        return src
        except Exception:
            pass
    return None


# ── Main ─────────────────────────────────────────────────────────────────────

async def main() -> None:
    print("=== Elezzjoni.mt Candidate Enrichment Pipeline ===\n")
    print(f"  SKIP_DISCOVERY = {SKIP_DISCOVERY}")
    print(f"  ENRICH_ALL     = {ENRICH_ALL}")
    print(f"  DRY_RUN        = {DRY_RUN}")
    print(f"  AUTH STATE     = {'state.json found' if os.path.exists(STATE_JSON) else 'not found (anonymous)'}\n")

    supabase: Client = create_client(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY)

    # Start Ollama if it isn't already running
    ollama_proc = await ensure_ollama_running()

    # Fetch candidates — by default only those without a score yet
    q = supabase.table("candidates").select(
        "id, full_name, photo_url, social_links, party_reliance_score"
    )
    if not ENRICH_ALL:
        q = q.is_("party_reliance_score", "null")
    rows = q.execute().data

    if not rows:
        print("Nothing to process. Set ENRICH_ALL_OVERRIDE=true to reprocess everyone.")
        return

    print(f"Processing {len(rows)} candidates…\n")

    # Semaphore = 1 keeps calls sequential, which also naturally respects Gemini's 15 RPM
    sem = asyncio.Semaphore(1)

    async with async_playwright() as pw:
        browser = await pw.chromium.launch(headless=True)

        async def process(c: dict) -> None:
            async with sem:
                name         = c["full_name"]
                social_links = c.get("social_links") or {}
                fb_url       = social_links.get("facebook")
                web_url      = social_links.get("website")

                print(f"── {name}")

                async with httpx.AsyncClient(headers={"User-Agent": UA}) as http:

                    # ── Stage 1: Discover links ───────────────────────────
                    if not SKIP_DISCOVERY and not fb_url:
                        print(f"   🔍 discovering social links…")
                        fb_url, web_url = await discover_links(name, http)
                        if fb_url:  print(f"   📘 Facebook: {fb_url}")
                        if web_url: print(f"   🌐 Website:  {web_url}")

                        if (fb_url or web_url) and not DRY_RUN:
                            updated = {**social_links}
                            if fb_url:  updated["facebook"] = fb_url
                            if web_url: updated["website"]  = web_url
                            supabase.table("candidates").update(
                                {"social_links": updated}
                            ).eq("id", c["id"]).execute()

                    # ── Stage 2: Scrape content ───────────────────────────
                    all_text    = ""
                    source_used = ""

                    # 2a: Facebook
                    if fb_url:
                        print(f"   📄 scraping Facebook…")
                        fb_text = await scrape_facebook(fb_url, browser)
                        if fb_text:
                            all_text    = fb_text
                            source_used = "Facebook page and posts"
                            print(f"   ✓  {len(fb_text.split())} words from Facebook")

                    scraped_photo: str | None = None   # og:image collected during scraping

                    # 2b: Personal website (trafilatura)
                    if web_url and len(all_text.split()) < MIN_WORDS:
                        print(f"   📄 scraping website…")
                        web_text, web_photo = await scrape_website(web_url, http)
                        if web_text:
                            all_text    = (all_text + "\n\n" + web_text).strip()
                            source_used = source_used or "personal website"
                            print(f"   ✓  {len(web_text.split())} words from website")
                        if web_photo and not scraped_photo:
                            scraped_photo = web_photo

                    # 2c: Local news search fallback
                    if len(all_text.split()) < MIN_WORDS:
                        print(f"   🔎 searching local news…")
                        news_text, news_photo = await scrape_news(name, http)
                        if news_text:
                            all_text    = (all_text + "\n\n" + news_text).strip()
                            source_used = source_used or "local news"
                            print(f"   ✓  {len(news_text.split())} words from news")
                        else:
                            print(f"   –  no news found")
                        if news_photo and not scraped_photo:
                            scraped_photo = news_photo

                    # ── Stage 2 (photo): resolve in priority order ────────
                    # 1. Facebook Graph API  2. og:image from scraped pages
                    # 3. Wikidata Commons    4. Wikipedia thumbnail
                    photo_url = c.get("photo_url")
                    if not photo_url:
                        if fb_url:
                            photo_url = await fetch_facebook_photo(fb_url, http)
                        if not photo_url and scraped_photo:
                            photo_url = scraped_photo
                        if not photo_url:
                            _, _, wd_photo = await wikidata_lookup(name, http)
                            photo_url = wd_photo
                        if not photo_url:
                            photo_url = await fetch_wikipedia_photo(name, http)
                        if photo_url:
                            print(f"   📷 photo found")

                    # ── Stage 3: Ollama enrichment ────────────────────────
                    enrichment: dict = {}
                    if all_text:
                        print(f"   🤖 enriching with {OLLAMA_MODEL}…")
                        enrichment = await enrich(name, all_text, source_used)

                        if enrichment.get("personal_stances"):
                            score = enrichment.get("party_reliance_score", "?")
                            n_stances = len(enrichment["personal_stances"])
                            n_quotes  = len(enrichment.get("key_quotes", []))
                            print(f"   ✓  score={score} · {n_stances} stances · {n_quotes} quotes")

                            # Translate to Maltese
                            print(f"   🇲🇹 translating to Maltese…")
                            all_en = (
                                enrichment["personal_stances"] +
                                enrichment.get("key_quotes", []) +
                                [enrichment.get("score_justification", "")]
                            )
                            all_mt = await translate_to_maltese(all_en)
                            n_stances = len(enrichment["personal_stances"])
                            n_quotes  = len(enrichment.get("key_quotes", []))
                            enrichment["personal_stances_mt"]    = all_mt[:n_stances]
                            enrichment["key_quotes_mt"]          = all_mt[n_stances:n_stances + n_quotes]
                            enrichment["score_justification_mt"] = all_mt[-1]
                        else:
                            print(f"   –  no policy content found in scraped text")
                    else:
                        print(f"   –  no content scraped (no links found or all sources blocked)")

                    # ── Stage 4: Save to Supabase ─────────────────────────
                    update: dict = {}

                    if enrichment:
                        update["party_reliance_score"]    = enrichment.get("party_reliance_score")
                        update["score_justification"]     = enrichment.get("score_justification")
                        update["personal_stances"]        = enrichment.get("personal_stances", [])
                        update["key_quotes"]              = enrichment.get("key_quotes", [])
                        update["score_justification_mt"]  = enrichment.get("score_justification_mt")
                        update["personal_stances_mt"]     = enrichment.get("personal_stances_mt", [])
                        update["key_quotes_mt"]           = enrichment.get("key_quotes_mt", [])

                    if photo_url:
                        update["photo_url"] = photo_url

                    if update:
                        update["last_updated"] = datetime.now(timezone.utc).isoformat()
                        if DRY_RUN:
                            print(f"   [DRY RUN] would write: {list(update.keys())}")
                            if "party_reliance_score" in update:
                                print(f"   [DRY RUN] score={update['party_reliance_score']} — {update.get('score_justification', '')}")
                        else:
                            supabase.table("candidates").update(update).eq("id", c["id"]).execute()

                print()

        await asyncio.gather(*[process(c) for c in rows])
        await browser.close()

    # Stop Ollama if we were the ones who started it
    if ollama_proc is not None:
        print("  🦙 stopping Ollama…")
        ollama_proc.terminate()

    print("=== Done ===")


if __name__ == "__main__":
    asyncio.run(main())
