-- ============================================================
-- Seed: 2022–2027 Parliament Members as test candidates
-- ============================================================

INSERT INTO candidates (full_name, party_id, districts, incumbent)
SELECT full_name, p.id, districts, true
FROM (VALUES
  -- Labour Party (PL)
  ('Robert Abela',              'PL', ARRAY[2]),
  ('Christopher Agius',         'PL', ARRAY[2]),
  ('Alison Zerafa Civelli',     'PL', ARRAY[2]),
  ('Glenn Bedingfield',         'PL', ARRAY[2]),
  ('Chris Fearne',              'PL', ARRAY[3]),
  ('Carmelo Abela',             'PL', ARRAY[3]),
  ('Andy Ellul',                'PL', ARRAY[3]),
  ('Ray Abela',                 'PL', ARRAY[3]),
  ('Byron Camilleri',           'PL', ARRAY[4]),
  ('Jonathan Attard',           'PL', ARRAY[4]),
  ('Chris Bonett',              'PL', ARRAY[4]),
  ('Katya De Giovanni',         'PL', ARRAY[4]),
  ('Miriam Dalli',              'PL', ARRAY[5]),
  ('Owen Bonnici',              'PL', ARRAY[5]),
  ('Stefan Zrinzo Azzopardi',   'PL', ARRAY[5]),
  ('Omar Farrugia',             'PL', ARRAY[5]),
  ('Silvio Schembri',           'PL', ARRAY[6]),
  ('Roderick Galdes',           'PL', ARRAY[6]),
  ('Rosianne Cutajar',          'PL', ARRAY[6]),
  ('Ian Borg',                  'PL', ARRAY[7]),
  ('Julia Farrugia Portelli',   'PL', ARRAY[7]),
  ('Malcolm Paul Agius Galea',  'PL', ARRAY[7]),
  ('Edward Zammit Lewis',       'PL', ARRAY[8]),
  ('Clyde Caruana',             'PL', ARRAY[8]),
  ('Rebecca Buttigieg',         'PL', ARRAY[9]),
  ('Randolph De Battista',      'PL', ARRAY[9]),
  ('Clifton Grima',             'PL', ARRAY[10]),
  ('Michael Falzon',            'PL', ARRAY[10]),
  ('Alex Muscat',               'PL', ARRAY[11]),
  ('Romilda Baldacchino Zarb',  'PL', ARRAY[11]),
  ('Michael Farrugia',          'PL', ARRAY[12]),
  ('Clayton Bartolo',           'PL', ARRAY[12]),
  ('Clint Camilleri',           'PL', ARRAY[13]),
  ('Anton Refalo',              'PL', ARRAY[13]),
  ('Jo Etienne Abela',          'PL', ARRAY[13]),
  ('Deo Debattista',            'PL', ARRAY[1]),
  ('Toni Bezzina',              'PL', ARRAY[]::integer[]),
  ('Ian Vassallo Hagi',         'PL', ARRAY[]::integer[]),
  ('Alicia Bugeja Said',        'PL', ARRAY[]::integer[]),
  ('Cressida Galea',            'PL', ARRAY[]::integer[]),
  ('Abigail Camilleri',         'PL', ARRAY[]::integer[]),
  ('Amanda Spiteri Grech',      'PL', ARRAY[]::integer[]),
  ('Naomi Cachia',              'PL', ARRAY[]::integer[]),
  ('Davina Sammut Hili',        'PL', ARRAY[]::integer[]),

  -- Nationalist Party (PN)
  ('Keith Azzopardi Tanti',     'PN', ARRAY[1]),
  ('Aaron Farrugia',            'PN', ARRAY[1]),
  ('Darren Carabott',           'PN', ARRAY[1]),
  ('Mario de Marco',            'PN', ARRAY[1]),
  ('Stephen Spiteri',           'PN', ARRAY[2]),
  ('Carmelo Mifsud Bonnici',    'PN', ARRAY[3]),
  ('Mark Anthony Sammut',       'PN', ARRAY[4]),
  ('Stanley Zammit',            'PN', ARRAY[5]),
  ('Jerome Caruana Cilia',      'PN', ARRAY[6]),
  ('Ryan Callus',               'PN', ARRAY[6]),
  ('Rebekah Cilia',             'PN', ARRAY[7]),
  ('Charles Azzopardi',         'PN', ARRAY[7]),
  ('Beppe Fenech Adami',        'PN', ARRAY[8]),
  ('Adrian Delia',              'PN', ARRAY[8]),
  ('Justin Schembri',           'PN', ARRAY[8]),
  ('Karol Aquilina',            'PN', ARRAY[9]),
  ('Graziella Attard Previ',    'PN', ARRAY[9]),
  ('Ivan J Bartolo',            'PN', ARRAY[9]),
  ('Joe Giglio',                'PN', ARRAY[10]),
  ('Albert Buttigieg',          'PN', ARRAY[10]),
  ('Graham Bencini',            'PN', ARRAY[10]),
  ('David Agius',               'PN', ARRAY[11]),
  ('Bernard Grech',             'PN', ARRAY[11]),
  ('Ivan Bartolo',              'PN', ARRAY[11]),
  ('Ivan Castillo',             'PN', ARRAY[12]),
  ('Robert Cutajar',            'PN', ARRAY[12]),
  ('Graziella Galea',           'PN', ARRAY[12]),
  ('Alex Borg',                 'PN', ARRAY[13]),
  ('Chris Said',                'PN', ARRAY[13]),
  ('Janice Chetcuti',           'PN', ARRAY[]::integer[]),
  ('Paula Mifsud Bonnici',      'PN', ARRAY[]::integer[]),
  ('Julie Zahra',               'PN', ARRAY[]::integer[]),
  ('Bernice Bonello',           'PN', ARRAY[]::integer[]),
  ('Claudette Buttigieg',       'PN', ARRAY[]::integer[]),
  ('Eve Borg Bonello',          'PN', ARRAY[]::integer[])

) AS data(full_name, abbr, districts)
JOIN parties p ON p.abbreviation = data.abbr;
